### PR TITLE
Test properly the result of the calls to sproxyd.

### LINKED ISSUE #19: Apache 2.4 install is broken on Centos
Since https://github.com/scality/openstack-ci-scripts/pull/17/, one can choose to use Apache 2.4 in front of Sproxyd on Centos.

This setup is not working properly : try running `wget  http://localhost:81/proxy/chord_path/.conf` and you bill get a 0 bytes length response.

Before fixing this we should fix the way we test the validity of the installation, as the Jenkins job did not detect this : https://37.187.159.67:5443/job/ring-install-test/48/

### PR DESCRIPTION
**Pull request by cazino**
And also use Apache 2.2 by default on Centos instead of 2.4

That PR should close https://github.com/scality/openstack-ci-scripts/issues/19

A first run to check that Apche2.4 misbehaviour is properly detected : https://37.187.159.67:5443/job/ring-install-test/51/

A second to test that the default behaviour is now not to use Apache 2.4: https://37.187.159.67:5443/job/ring-install-test/52/

I propose to keep the apache 2.4 configuration code around for the moment since it is not completely clear why it is not working.

### CODE REVIEW

File: jenkins/ring-install.sh [hunk 1]
```diff
@@ -443,8 +443,15 @@ function purge_ring {
 function test_sproxyd {
     for path in 'chord_path' 'arc'; do
         local r=$RANDOM
+        local put_response=${r}_put
+        local get_response=${r}_get
         local url="http://localhost:81/proxy/${path}/${r}"
-        curl -v -XPUT -H "Expect:" -H "x-scal-usermd: bXl1c2VybWQ=" ${url} --data-binary @/etc/hosts
-        curl -v -XGET ${url}
+        curl -i -XPUT -H "Expect:" -H "x-scal-usermd: bXl1c2VybWQ=" ${url} --data-binary @/etc/hosts -o $put_response
+        cat $put_response
```
Comment (JordanP) [inline jenkins/ring-install.sh:450]: Why do you cat the file ?

I would do everything in one line.
`curl -i -XPUT -H "Expect:" -H "x-scal-usermd: bXl1c2VybWQ=" ${url} --data-binary @/etc/hosts | grep '200 OK'`

Comment (cazino) [inline jenkins/ring-install.sh:450]: To get more information on what went wrong in case of a failure, with the pipe solution we get no output.

File: jenkins/ring-install.sh [hunk 2]
```diff
@@ -443,8 +443,15 @@ function purge_ring {
...
+        grep '200 OK' $put_response
+        curl -i -XGET ${url} -o $get_response
+        cat $get_response
+        grep '200 OK' $get_response
+        grep "Content-Length: $(stat --printf="%s" /etc/hosts)" $get_response
```
Comment (JordanP) [inline jenkins/ring-install.sh:455]: You should 
`rm ${r}_put ${r}_get`
If they exist.

Comment (cazino) [inline jenkins/ring-install.sh:455]: Done, it works : https://37.187.159.67:5443/job/ring-install-test/54/

**Comment by JordanP** [comment]
LGTM
